// <auto-generated />
namespace ApiCrud.BO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class atualizandoClasse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizandoClasse));
        
        string IMigrationMetadata.Id
        {
            get { return "201802062046572_atualizandoClasse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
